
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8089:8089"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/campus_virtual
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    restart: always
    command: >
      sh -c "cd prisma &&
      prisma migrate deploy &&
      cd .. &&
      echo 'Esperando que la base de datos esté disponible...' &&
        until mysqladmin ping -h db --user=root --password=root --silent; do
        sleep 1;
      done &&
      echo 'Base de datos lista, ejecutando script de inicialización...' &&
      mysql -h db -u root -proot campus_virtual < /app/scripts/init.sql &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=campus_virtual
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
  uploads_data:
