version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlserver://sa:StrongPwd2025@db:1433;database=campus_virtual;trustServerCertificate=true
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    restart: always
    command: >
      sh -c "cd prisma &&
      prisma migrate deploy &&
      cd .. &&
      echo 'Esperando que la base de datos esté disponible...' &&
      until /opt/mssql-tools/bin/sqlcmd -S db -U sa -P StrongPwd2025 -d campus_virtual -Q 'SELECT 1'; do
        sleep 1;
      done &&
      echo 'Base de datos lista, ejecutando script de inicialización...' &&
      /opt/mssql-tools/bin/sqlcmd -S db -U sa -P StrongPwd2025 -d campus_virtual -i /app/scripts/init.sql &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPwd2025
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P StrongPwd2025 -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqlserver_data:
  uploads_data:
