version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/campus_virtual
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    restart: always
    command: sh -c "cd prisma && prisma migrate deploy && cd .. && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=campus_virtual
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  uploads_data:
